services:
  frontend:
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro # mount the config file for dev
      - ./frontend/nginx-snippets:/etc/nginx/snippets:ro # mount the config file for dev
      - ./frontend/testcerts:/etc/letsencrypt:ro  # mount test certs (read-only)
      - ./frontend/dist:/usr/share/nginx/html:ro # mount build files for dev
      - nginx_logs:/var/log/nginx
    develop:  # âœ… This goes under the service
      watch:
        - path: ./frontend/nginx.conf
          action: restart
          # target: /etc/nginx/conf.d/default.conf #no need since im mounting it already
