services:
  db:
    image: postgres
    volumes:
      - ~/.local/share/postgres_data/marketmap_db:/var/lib/postgresql/data
    ports:
      # exposing the postgresql for local dev
      - "54321:5432"
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - COASV_SECRET_KEY=insecurerandomsecretkeychangeit!=z_yb25jv_%%)o(+d6
      - COASV_DEBUG_VALUE=True
      - COASV_DB_HOST=db
      - COASV_DB_NAME=postgres_db
      - COASV_DB_USER=postgres_user
      - COASV_DB_PASS=postgres_password
    depends_on:
      - db
